<<<<<<< HEAD
# .streamlit/secrets.toml
 #OPENAI_API_KEY = "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"
=======
.streamlit/secrets.toml
0PENAI_API_KEY = "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"
>>>>>>> 60e94a6b62ec85e653f22d6fc10f5015ad04fd54
